#!/usr/bin/env bash
echo "virsh $*" >> "${MOCKLOG:-/dev/null}"
case "$1" in
  net-info)   [ "${VIRSH_NET_EXISTS:-0}" = "1" ] && exit 0 || exit 1 ;;
  dominfo)    [ "${VIRSH_DOM_EXISTS:-0}" = "1" ] && exit 0 || exit 1 ;;
  domstate)   echo "${VIRSH_DOMSTATE:-running}" ;;
  net-dumpxml)  echo "<network><name>$2</name></network>" ;;
  dumpxml)      echo "<domain><name>$2</name><tpm model='tpm-crb'><backend version='2.0'/></tpm><loader secure='yes'/><graphics type='spice'><listen type='address' address='127.0.0.1'/></graphics></domain>" ;;
  *) : ;;
esac
exit 0
